export const diagnosticsCopy = {
  title: "Diagnostics LCU",
  subtitle: "Vérifie la connexion locale à League et exporte un rapport expurgé.",
  refresh: "Actualiser",
  run: "Tester les endpoints sûrs",
  running: "Tests en cours…",
  export: "Exporter le rapport",
  includeRiotId: "Inclure mon Riot ID dans l’export",
  copy: "Copier le rapport",
  connection: "Connexion League",
  gameData: "Sources de données",
  source: "Source active",
  version: "Version du jeu",
  cache: "Cache disponible",
  available: "Disponible",
  unavailable: "Indisponible",
  requests: "Requêtes récentes",
  events: "Événements récents",
  errors: "Erreurs récentes",
  endpoints: "Tests autorisés",
  search: "Filtrer les journaux",
  all: "Tout",
  onlyErrors: "Erreurs",
  automation: "Automation",
  data: "Données",
  webview: "WebView",
  lcuFilter: "LCU",
  notRun: "Non testé",
  latency: "Latence récente",
  noEntries: "Aucune entrée pour ce filtre.",
  noLeague: "League n’est pas connecté. Les tests seront réessayés quand le client sera ouvert.",
  redacted: "Les identifiants et secrets sont masqués par défaut.",
  exportFailed: "Impossible d’exporter le rapport de diagnostics.",
  runFailed: "Les tests de diagnostic ont échoué.",
  success: "OK",
  failure: "Échec",
  milliseconds: "ms",
  datadragon: "Data Dragon (secours)",
  lcu: "LCU local",
  cacheSource: "Cache local",
  mixed: "Sources combinées",
  none: "Aucune",
  settingsDescription: "Examiner la connexion LCU, les événements et les erreurs expurgés.",
  testResults: "Résultats des tests",
  copied: "Rapport copié dans le presse-papiers.",
  viewJson: "Voir JSON",
  jsonTitle: "JSON de l’événement",
  jsonDescription: "Payload expurgé reçu du flux LCU.",
} as const;
